# Generated by Django 5.2.17 on 2026-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
