# Generated by Django 5.2.17 on 2026-08-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_alter_cluster_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='extra',
        ),
    ]
