# Generated by Django 5.2.17 on 2026-08-23 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduleBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pod_name', models.CharField(max_length=255)),
                ('source_path', models.TextField()),
                ('schedule', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_backups', to='applications.app')),
            ],
        ),
    ]
