# Generated by Django 5.2.17 on 2026-08-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backup_is_scheduled_schedulebackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='pod_name',
        ),
        migrations.RemoveField(
            model_name='schedulebackup',
            name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='schedulebackup',
            name='pod_name',
        ),
    ]
