# Generated by Django 5.2.17 on 2026-08-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_remove_backup_pod_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='pod_name',
            field=models.CharField(blank=True),
        ),
    ]
